реализовать add-bookings
biscuitka/java-shareit pull request #3
Opened 2023-07-25 14:09 UTC by biscuitka

2023-07-25 21:46 UTC, NikolaiDem requested changes

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  @Data
equals и hashCode переопределять не нужно

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    public static Booking getValidatedBooking(BookingRepository bookingRepository, long bookingId) {
Репозиторий не должен внедряться в модель. Домен не должен зависеть от инфраструктурных единиц, это ядро приложения

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(required = false, defaultValue = HeaderConstants.DEFAULT_STATE_VALUE)
Если указано дефолтное значение, то required = false можно удалить, аналогично ниже

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +
Еще лучше проверить, что вещь не забронирована никем другим на запрашиваемые даты.

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
@Transactional можно вынести на уровень класса
Аналогично для остальных сервисов

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .stream().map(BookingMapper::fromBookingToDtoOut).collect(Collectors.toList());
Кодстайл : методы стрима лучше расположить в новых строках

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .stream().map(BookingMapper::fromBookingToDtoOut).collect(Collectors.toList());
.stream().map(BookingMapper::fromBookingToDtoOut).collect(Collectors.toList()) дублируется много раз

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b where b.booker.id = ?1 and ?2 between b.start and b.end order by b.start desc")
Можно обойтись без кастомных запросов с помощью query методов?)

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/comment/Comment.java
> +@Data
equals и hashCode для модели переопределять нет необходимости

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  @Data
equals и hashCode для модели переопределять нет необходимости
Аналогично для остальных моделей

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    public static Item getValidatedItem(ItemRepository itemRepository, long itemId) {
Репозиторий не должен внедряться в модель. Домен не должен зависеть от инфраструктурных единиц, это ядро приложения
Аналогично для остальных моделей

2023-07-25 21:46 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .peek(this::setLastBooking)
Проблема N+1 запроса. Необходимо получить все бронирования и комментарии одним запросом в БД, а не обращаться к репозиторию в каждой итерации )

2023-07-27 05:58 UTC, biscuitka commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
Я правильно понимаю, что когда я выношу @transactional на уровень класса, то для всех методов будут создаваться транзакции, но для методов гет все равно нужно будет явно указать  @Transactional(readOnly = true)

2023-07-27 06:06 UTC, biscuitka commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b where b.booker.id = ?1 and ?2 between b.start and b.end order by b.start desc")
Попробую снова, но по мере выполнения ТЗ и пришла к таким разношерстным вариантам, так как иначе не получалось)

2023-07-27 11:25 UTC, biscuitka commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b where b.booker.id = ?1 and ?2 between b.start and b.end order by b.start desc")
Бинго! Это получилось, оказалось проще чем было в начале работы над ТЗ)

2023-07-27 22:56 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        boolean isConflicting = bookings.stream().anyMatch(booking ->
boolean isConflicting = !bookings.stream().allMatch(booking ->
                !booking.getStart().isBefore(bookingDtoIn.getEnd()) || !booking.getEnd().isAfter(bookingDtoIn.getEnd())
        );

2023-07-27 22:56 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    @Transactional
Да

2023-07-27 23:09 UTC, NikolaiDem requested changes

2023-07-27 23:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Comment> comments = commentRepository.findAll();
Все комментарии выгружать не нужно. Можно выгрузить только по списку items

2023-07-27 23:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                    .filter(commentDto -> itemDto.getComments().contains(commentDto))
А где заполняются комментарии в itemDto, чтобы условие itemDto.getComments().contains(commentDto) было когда-нибудь true?

2023-07-27 23:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            List<CommentDto> itemComments = commentDtos.stream()
Чтобы избавиться от вложенного цикла, лучше comments преобразовать в мапу, где ключ - itemId (или Item), а значение - список комментариев.

2023-07-27 23:09 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        .max(Comparator.comparing(Booking::getEnd))
Почему сортировка по end?

2023-07-31 06:07 UTC, biscuitka commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                        .max(Comparator.comparing(Booking::getEnd))
Чтобы найти самое последнее бронирование, у next просто использовала findFirst, или лучше одинаково тогда использовать сортировку и там и там? Т.е для next это будет min(Comparator.comparing(Booking::getStart))

2023-07-31 15:37 UTC, NikolaiDem approved these changes

2023-08-03 07:57 UTC, merged