Реализовать запросы и тестирование
biscuitka/java-shareit pull request #4
Opened 2023-08-11 11:52 UTC by biscuitka

2023-08-12 09:22 UTC, NikolaiDem requested changes

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDtoOut> getAllBookingByUser(long userId, StateOfBooking stateOfBooking, int from, int size);
Вместо набора параметров лучше передать Pageable.
Аналогично ниже

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                booking.getStart().isAfter(bookingDtoIn.getEnd()) || booking.getEnd().isBefore(bookingDtoIn.getStart())
Пусть существующее бронирование происходит с 13:00 до 15:00, а новое с 15:00 до 17:00.
Будет ли пройдена валидация в таком случае?

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/AccessDeniedException.java
> +    public HttpStatus getHttpStatus() {
Можно использовать lombok вместо шаблонного кода.
Аналогично для остальных исключений

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoRequested.java
> +    public ItemDtoRequested(Item item) {
Dto - это объект из внешнего мира, он ничего не должен знать о модели данных. Преобразование Item в Dto лучше сделать в маппере

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    List<ItemDto> getBySearch(String search, int from, int size);
Вместо набора параметров лучше передать Pageable.
Аналогично ниже

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>          User owner = UserServiceImpl.getValidatedUser(userRepository, userId);
Зачем передавать репозиторий, если в сервисе он уже есть?)

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            ItemRequest request = ItemRequestServiceImpl.getValidatedRequest(requestRepository, requestId);
Зачем передавать репозиторий, если в сервисе он уже есть?)
И вообще репозитории передавать в сервисы не нужно. Репозиторий - это вспомогательный объект для выполнения бизнес-функции. Это как прийти к стоматологу, принести все необходимые инструменты и сказать : "нужно вот в этом месте этим инструментом сделать такое-то действие"...)
Аналогично в остальных методах

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    List<RequestDtoWithItemsOut> getAllByOwner(long userId, int from, int size);
Вместо набора параметров лучше передать Pageable.
Аналогично ниже

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        User user = UserServiceImpl.getValidatedUser(userRepository, userId);
Передавать репозитории в другие сервисы не нужно

2023-08-12 09:22 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/RequestMapper.java
> +    public static RequestDtoWithItemsOut fromRequestToDtoWithItemsOut(ItemRequest request, List<Item> items) {
Нужно передать только те items, которые относятся к данному request, чтобы не перебирать лишние предметы в цикле на 36 строке

2023-08-17 05:24 UTC, biscuitka commented
забыла сменить название коммита "написать тест на конструктор" 853cd1a, по факту там ломбок вместо геттеров и замена на pageable.

2023-08-18 05:39 UTC, NikolaiDem requested changes

2023-08-18 05:39 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/util/EntityValidator.java
> +public class EntityValidator {
Этот класс создает сильную связанность между классами, которые его используют. От таких классов лучше избавиться)
В сервисах можно явно использовать repositoru.findById(...).orElseThrow(...);
Или можно в репозитории добавить кастомные методы, которые бросят исключение, если объект не найден

2023-08-18 12:05 UTC, NikolaiDem approved these changes

2023-08-18 14:21 UTC, merged